x-service-template: &service-template
  build: . 
  init: true
  restart: always
services:
  aggregator: 
    <<: *service-template
    environment:
      FLASK_APP: ./aggregator
      FLASK_DEBUG: true
  
    ports:
      - 5000:5000
      - 5678:5678 #For debugpy

    volumes:
      - .:/usr/src/app #Attaching project dir for debugging, not good for production

  api1:  &api-template
    <<: *service-template
    environment: 
      FLASK_APP: ./api

  api2: *api-template
  api3: *api-template
